name: Deploy API

on:
  push:
    branches:
      - custom

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t new-api .

      - name: Compress
        run: |
          docker save new-api | gzip > new-api.tar.gz

      - name: Transfer image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          source: "new-api.tar.gz"
          target: "/tmp/new-api.tar.gz"

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker load -i /tmp/new-api.tar.gz
            docker compose pull
            docker compose up -d
            rm -rf /tmp/new-api.tar.gz

      - name: Send notification
        run: |
          curl -X POST -H 'Content-Type: application/json' \
            -d '{"message": "API deployed successfully."}' \
            ${{ env.NTFY_URL }}/${{ env.NTFY_TOPIC }}
